export const EMOJI_MAP: Record<string, string> = {
	love: "❤️",
	fire: "🔥",
	perfect: "💯",
	wow: "😲",
	idea: "💡",
	money: "💰",
	cash: "💰",
	time: "⏱️",
	clock: "⏳",
	fast: "⚡",
	quick: "⚡",
	slow: "🐢",
	star: "⭐",
	world: "🌍",
	earth: "🌎",
	sun: "☀️",
	moon: "🌙",
	win: "🏆",
	winner: "🥇",
	success: "📈",
	growth: "🌱",
	happy: "😊",
	sad: "😢",
	angry: "😠",
	funny: "😂",
	laugh: "🤣",
	car: "🚗",
	book: "📖",
	music: "🎵",
	song: "🎶",
	video: "📹",
	movie: "🎬",
	camera: "📷",
	photo: "📸",
	computer: "💻",
	laptop: "💻",
	phone: "📱",
	call: "📞",
	message: "💬",
	mail: "📧",
	email: "✉️",
	home: "🏠",
	house: "🏡",
	food: "🍕",
	eat: "🍔",
	drink: "🥤",
	water: "💧",
	coffee: "☕",
	sleep: "😴",
	bed: "🛏️",
	gym: "🏋️",
	workout: "💪",
	run: "🏃",
	walk: "🚶",
	game: "🎮",
	play: "▶️",
	stop: "⏹️",
	pause: "⏸️",
	record: "⏺️",
	yes: "✅",
	no: "❌",
	good: "👍",
	bad: "👎",
	up: "⬆️",
	down: "⬇️",
	left: "⬅️",
	right: "➡️",
	warning: "⚠️",
	danger: "☢️",
	magic: "✨",
	sparkle: "✨",
	cool: "😎",
	mind: "🧠",
	brain: "🧠",
	heart: "💖",
	broken: "💔",
	alien: "👽",
	robot: "🤖",
	ghost: "👻",
	skull: "💀",
	party: "🎉",
	celebrate: "🎊",
	gift: "🎁",
	present: "🎁",
	birthday: "🎂",
	cake: "🍰",
	sweet: "🍬",
	candy: "🍭",
	dog: "🐶",
	cat: "🐱",
	pet: "🐾",
	fly: "✈️",
	travel: "🧳",
	holiday: "🏖️",
	beach: "⛱️",
	ocean: "🌊",
	mountain: "⛰️",
	forest: "🌲",
	tree: "🌳",
	flower: "🌸",
	rose: "🌹",
};

export function injectEmojis(text: string): string {
	const words = text.split(" ");
	const resultText = words.map((word) => {
		const cleanWord = word.toLowerCase().replace(/[^a-z]/g, "");
		if (EMOJI_MAP[cleanWord]) {
			return `${word} ${EMOJI_MAP[cleanWord]}`;
		}
		return word;
	}).join(" ");
	return resultText;
}
