export const SARVAM_VOICES = [
    { id: "shubh", name: "Shubh (Male) - Friendly", gender: "male" },
    { id: "priya", name: "Priya (Female) - Upbeat", gender: "female" },
    { id: "suhani", name: "Suhani (Female) - Soothing", gender: "female" },
    { id: "ashutosh", name: "Ashutosh (Male) - Traditional", gender: "male" },
    { id: "ritu", name: "Ritu (Female) - Approachable", gender: "female" },
    { id: "amit", name: "Amit (Male) - Formal", gender: "male" },
    { id: "sumit", name: "Sumit (Male) - Warm", gender: "male" },
    { id: "pooja", name: "Pooja (Female) - Encouraging", gender: "female" },
    { id: "manan", name: "Manan (Male) - Consistent", gender: "male" },
    { id: "simran", name: "Simran (Female) - Conversational", gender: "female" },
    { id: "rahul", name: "Rahul (Male) - Composed", gender: "male" },
    { id: "kavya", name: "Kavya (Female) - Everyday", gender: "female" },
    { id: "anushka", name: "Anushka (Female)", gender: "female" },
    { id: "abhilash", name: "Abhilash (Male)", gender: "male" },
    { id: "vidya", name: "Vidya (Female)", gender: "female" },
    { id: "arya", name: "Arya (Female)", gender: "female" },
    { id: "karun", name: "Karun (Male)", gender: "male" },
    { id: "hitesh", name: "Hitesh (Male)", gender: "male" },
    { id: "aditya", name: "Aditya (Male)", gender: "male" },
    { id: "neha", name: "Neha (Female)", gender: "female" },
    { id: "ishita", name: "Ishita (Female)", gender: "female" },
    { id: "shreya", name: "Shreya (Female)", gender: "female" },
    { id: "ratan", name: "Ratan (Male)", gender: "male" },
    { id: "varun", name: "Varun (Male)", gender: "male" },
];
